spring:
  datasource:
    url: jdbc:mysql://localhost:3510/socks?useSSL=false
    username: root
    password: y12345
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
